-- Homepage settings: announcement bar, comparison table, study roadmap, feature strip, testimonials, FAQ
-- Public read for site_settings (homepage needs it)
DROP POLICY IF EXISTS "Public read site_settings" ON site_settings;
CREATE POLICY "Public read site_settings" ON site_settings FOR SELECT USING (true);

-- Seed homepage keys with prepopulated values
INSERT INTO site_settings (key, value) VALUES
  ('announcement_bar', '{"enabled":true,"variant":"A","message":"🔥 Limited Time: Mega Bundle ₹899 (Save 60%) →","href":"/product/complete-japanese-n5-n1-mega-bundle"}'::jsonb),
  ('bundle_comparison', '{"rows":[{"label":"Best for","n5":"Beginner foundation","n4":"Everyday Japanese","n3":"Intermediate bridge","n2":"Professional / Keigo","n1":"Near-native academic","mega":"Everything + roadmap + papers"},{"label":"Kanji","n5":"~80","n4":"~166","n3":"~369","n2":"~367","n1":"~1130","mega":"All"},{"label":"Vocabulary","n5":"~800","n4":"~1500","n3":"~3750","n2":"~6000","n1":"~10000","mega":"All"},{"label":"Grammar","n5":"~40","n4":"~50","n3":"~100","n2":"~150","n1":"~200","mega":"All"},{"label":"Mock tests","n5":"✓ 5","n4":"✓ 5","n3":"✓ 5","n2":"✓ 5","n1":"✓ 5","mega":"✓ All"},{"label":"Audio","n5":"✓","n4":"✓","n3":"✓","n2":"✓","n1":"✓","mega":"✓"}],"prices":{"n5":199,"n4":299,"n3":399,"n2":499,"n1":599,"mega":899}}'::jsonb),
  ('study_roadmap', '{"headline":"Worksheets + Mock Tests + Audio at every level","bullets":["400+ hours material (Mega)","Lifetime access"],"ctaText":"Buy Mega Bundle","megaSlug":"complete-japanese-n5-n1-mega-bundle"}'::jsonb),
  ('homepage_feature_strip', '[{"label":"Worksheets + Answer Keys","icon":"check"},{"label":"JLPT-style Mock Tests","icon":"check"},{"label":"Listening Practice","icon":"check"},{"label":"Structured Roadmap (Mega)","icon":"check"},{"label":"Instant Download","icon":"check"},{"label":"Lifetime access via Library","icon":"check"}]'::jsonb),
  ('testimonials_about', '{"aboutText":"I help learners master Japanese from N5 to N1 with structured bundles, mock tests, and a clear roadmap.","aboutLink":"/start-here","aboutLinkText":"Read my story","testimonials":[],"fallbackMode":"why_this_works","whyBullets":["Structured study path (N5→N1)","JLPT-style mock tests at every level","Progressive grammar, vocab, kanji","Lifetime access via Library"]}'::jsonb),
  ('homepage_faq', '[{"q":"What do I get after payment?","a":"Instant access via email. You get a magic link to log in and download all PDFs, audio, and materials from your Library."},{"q":"How do I access downloads later?","a":"Log in with the same email you used to purchase. Your Library shows all your bundles. Download anytime, offline."},{"q":"Can I use on mobile?","a":"Yes. PDFs work on any device. Download once and study offline."},{"q":"Are these JLPT-aligned?","a":"Yes. Content follows official JLPT structure for grammar, vocabulary, and kanji at each level."},{"q":"Is it beginner friendly?","a":"Yes. N5 is for complete beginners. Take the placement quiz to find your level."},{"q":"What is your refund policy?","a":"Digital products are non-refundable. Preview samples before purchase."},{"q":"Can I upgrade later?","a":"Yes. Consider the Mega Bundle for best value — all levels + roadmap + extras at 60% off."}]'::jsonb)
ON CONFLICT (key) DO NOTHING;
